blueprint:
  name: Anunciar via Alexa
  description: Anuncia em todas as caixas Echo selecionadas
  domain: script
mode: queued
fields:
  mensagem:
    selector:
      text: null
    name: Mensagem a ser reproduzida
    description: Ela vai falar o que vocÊ digita
    required: true
  onde_anunciar:
    selector:
      entity:
        filter:
          - integration: alexa_media
            domain: media_player
        multiple: true
    name: Onde Anunciar
    required: true
    default: []
    description: Escolha suas Alexas
  volume:
    selector:
      number:
        min: 0.1
        max: 1
        step: 0.1
    default: 10
    name: Volume
    description: Deslize a barra para ajustar o volume do anúncio
sequence:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: "{{ volume }}"
    target:
      entity_id: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.alexa_media
    data:
      message: "{{ mensagem }}"
      data:
        type: announce
      target: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.5
    target:
      entity_id: "{{ onde_anunciar }}"
icon: mdi:bullhorn
